In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Fast_Food_Restaurants_US.csv")
df

,Unnamed: 0,address,categories,city,country,latitude,longitude,name,postalCode,province,websites
0,0,800 N Canal Blvd,American Restaurant and Fast Food Restaurant,Thibodaux,US,29.814697,-90.814742,SONIC Drive In,70301,LA,https://locations.sonicdrivein.com/la/thibodau...
1,1,800 N Canal Blvd,Fast Food Restaurants,Thibodaux,US,29.814697,-90.814742,SONIC Drive In,70301,LA,https://locations.sonicdrivein.com/la/thibodau...
2,2,206 Wears Valley Rd,Fast Food Restaurant,Pigeon Forge,US,35.803788,-83.580553,Taco Bell,37863,TN,"http://www.tacobell.com,https://locations.taco..."
3,3,3652 Parkway,Fast Food,Pigeon Forge,US,35.782339,-83.551408,Arby's,37863,TN,"http://www.arbys.com,https://locations.arbys.c..."
4,4,2118 Mt Zion Parkway,Fast Food Restaurant,Morrow,US,33.562738,-84.321143,Steak 'n Shake,30260,GA,http://www.steaknshake.com/locations/23851-ste...
...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,3460 Robinhood Rd,Fast Food Restaurants,Winston-Salem,US,36.117563,-80.316553,Pizza Hut,27106,NC,http://www.pizzahut.com
9996,9996,3069 Kernersville Rd,Fast Food Restaurants,Winston-Salem,US,36.077718,-80.176748,Pizza Hut,27107,NC,http://www.pizzahut.com
9997,9997,838 S Main St,Fast Food Restaurants,Kernersville,US,36.111015,-80.089165,Pizza Hut,27284,NC,http://www.pizzahut.com
9998,9998,1702 Glendale Dr SW,Fast Food Restaurants,Wilson,US,35.719981,-77.945795,Pizza Hut,27893,NC,http://www.pizzahut.com
9999,9999,1405 W Broad St,Fast Food Restaurants,Elizabethtown,US,34.632778,-78.624615,Pizza Hut,28337,NC,"http://www.pizzahut.com,http://api.citygridmed..."

In [6]:
df.province.unique()

array(['LA', 'TN', 'GA', 'MI', 'CA', 'NY', 'TX', 'OH', 'SC', 'MS', 'IN',
       'MA', 'FL', 'MO', 'PA', 'IL', 'CT', 'KY', 'KS', 'IA', 'HI', 'ID',
       'NC', 'DE', 'AZ', 'WI', 'CO', 'AR', 'SD', 'WV', 'WY', 'VA', 'OR',
       'MD', 'WA', 'UT', 'NV', 'OK', 'ME', 'ND', 'NH', 'VT', 'NJ', 'NE',
       'MN', 'MT', 'AL', 'NM', 'AK', 'RI'], dtype=object)

In [23]:
stateGroup = df.groupby("province").count()
stateGroup

,Unnamed: 0,address,categories,city,country,latitude,longitude,name,postalCode,websites
province,,,,,,,,,,
AK,16,16,16,16,16,16,16,16,16,16
AL,6,6,6,6,6,6,6,6,6,6
AR,102,102,102,102,102,102,102,102,102,102
AZ,330,330,330,330,330,330,330,330,330,330
CA,1201,1201,1201,1201,1201,1201,1201,1201,1201,1201
CO,148,148,148,148,148,148,148,148,148,148
CT,53,53,53,53,53,53,53,53,53,53
DE,44,44,44,44,44,44,44,44,44,44
FL,621,621,621,621,621,621,621,621,621,621
GA,420,420,420,420,420,420,420,420,420,420
HI,32,32,32,32,32,32,32,32,32,32
IA,115,115,115,115,115,115,115,115,115,115
ID,51,51,51,51,51,51,51,51,51,51
IL,405,405,405,405,405,405,405,405,405,405
IN,254,254,254,254,254,254,254,254,254,254
KS,74,74,74,74,74,74,74,74,74,74
KY,166,166,166,166,166,166,166,166,166,166
LA,202,202,202,202,202,202,202,202,202,202
MA,205,205,205,205,205,205,205,205,205,205
MD,172,172,172,172,172,172,172,172,172,172
ME,25,25,25,25,25,25,25,25,25,25
MI,374,374,374,374,374,374,374,374,374,374
MN,199,199,199,199,199,199,199,199,199,199
MO,163,163,163,163,163,163,163,163,163,163
MS,55,55,55,55,55,55,55,55,55,55
MT,38,38,38,38,38,38,38,38,38,38
NC,295,295,295,295,295,295,295,295,295,295
ND,35,35,35,35,35,35,35,35,35,35
NE,87,87,87,87,87,87,87,87,87,87
NH,34,34,34,34,34,34,34,34,34,34
NJ,129,129,129,129,129,129,129,129,129,129
NM,78,78,78,78,78,78,78,78,78,78
NV,121,121,121,121,121,121,121,121,121,121
NY,352,352,352,352,352,352,352,352,352,352
OH,522,522,522,522,522,522,522,522,522,522
OK,166,166,166,166,166,166,166,166,166,166
OR,154,154,154,154,154,154,154,154,154,154
PA,383,383,383,383,383,383,383,383,383,383
RI,15,15,15,15,15,15,15,15,15,15
SC,188,188,188,188,188,188,188,188,188,188
SD,42,42,42,42,42,42,42,42,42,42
TN,302,302,302,302,302,302,302,302,302,302
TX,811,811,811,811,811,811,811,811,811,811
UT,63,63,63,63,63,63,63,63,63,63
VA,253,253,253,253,253,253,253,253,253,253
VT,15,15,15,15,15,15,15,15,15,15
WA,196,196,196,196,196,196,196,196,196,196
WI,189,189,189,189,189,189,189,189,189,189
WV,70,70,70,70,70,70,70,70,70,70
WY,29,29,29,29,29,29,29,29,29,29

In [24]:
stateGroup.columns

Index(['Unnamed: 0', 'address', 'categories', 'city', 'country', 'latitude',
       'longitude', 'name', 'postalCode', 'websites'],
      dtype='object')

In [25]:
stateGroup['count'] = stateGroup[stateGroup.columns[0]]

In [30]:
stateGroup = stateGroup['count']

In [33]:
stateGroup

province
AK      16
AL       6
AR     102
AZ     330
CA    1201
CO     148
CT      53
DE      44
FL     621
GA     420
HI      32
IA     115
ID      51
IL     405
IN     254
KS      74
KY     166
LA     202
MA     205
MD     172
ME      25
MI     374
MN     199
MO     163
MS      55
MT      38
NC     295
ND      35
NE      87
NH      34
NJ     129
NM      78
NV     121
NY     352
OH     522
OK     166
OR     154
PA     383
RI      15
SC     188
SD      42
TN     302
TX     811
UT      63
VA     253
VT      15
WA     196
WI     189
WV      70
WY      29
Name: count, dtype: int64

In [35]:
stateGroup.to_csv('count_by_state.csv')